[versions]
agp = "8.7.0"
androidMapsUtils = "3.8.2"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
places = "5.1.1"
mockitoCore = "5.11.0"
playServicesMaps = "18.1.0"
rules = "1.7.0"
playServicesLocation = "21.3.0"
glide = "4.16.0"

[libraries]
android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoCore" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }

